VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsLog"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' clsLog.Cls
' Copyright (C) 2008 Eric Evans
' ...

Option Explicit

' ...
Public Function WriteWarning(ByVal Source As String, ByVal sWarning As String)

    ' ...

End Function

' ...
Public Function WriteError(ByVal Source As String, ByVal Procedure As String, ByVal sError As String)

    ' ...

End Function

' ...
Public Function WriteEvent(ByVal Source As String, ByVal sEvent As String)

    ' ...

End Function

' ...
Public Function WriteDebug(ByVal Source As String, ByVal sDebugMessage As String)

    ' ...

End Function
