VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsMyClanObj"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' clsMyClanObj.cls
' Copyright (C) 2008 Eric Evans
' ...

Option Explicit

' ...
Public Property Get Name() As String

    ' ...

End Property

' ...
Public Property Get Rank() As Integer

    ' ...

End Property

' ...
Public Property Get Members() As Collection

    ' ...

End Property

